export const VERSE_OF_THE_DAY_365 = [
  { reference: 'John 3:16', text: 'For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.' },
  { reference: 'Psalm 23:1', text: 'The Lord is my shepherd; I shall not want.' },
  { reference: 'Philippians 4:13', text: 'I can do all things through Christ who strengthens me.' },
  { reference: 'Jeremiah 29:11', text: 'For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.' },
  { reference: 'Romans 8:28', text: 'And we know that in all things God works for the good of those who love him, who have been called according to his purpose.' },
  { reference: 'Isaiah 41:10', text: 'So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you.' },
  { reference: 'Matthew 6:33', text: 'But seek first his kingdom and his righteousness, and all these things will be given to you as well.' },
  { reference: 'Proverbs 3:5', text: 'Trust in the Lord with all your heart and lean not on your own understanding.' },
  { reference: 'Psalm 46:1', text: 'God is our refuge and strength, an ever-present help in trouble.' },
  { reference: 'Romans 12:2', text: 'Do not conform to the pattern of this world, but be transformed by the renewing of your mind.' },
  { reference: 'Joshua 1:9', text: 'Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.' },
  { reference: 'Ephesians 2:8', text: 'For it is by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God.' },
  { reference: 'Matthew 11:28', text: 'Come to me, all you who are weary and burdened, and I will give you rest.' },
  { reference: 'Psalm 119:105', text: 'Your word is a lamp for my feet, a light on my path.' },
  { reference: '2 Timothy 3:16', text: 'All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness.' },
  { reference: 'John 14:6', text: 'Jesus answered, I am the way and the truth and the life. No one comes to the Father except through me.' },
  { reference: 'Galatians 2:20', text: 'I have been crucified with Christ and I no longer live, but Christ lives in me.' },
  { reference: 'Romans 5:8', text: 'But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.' },
  { reference: '1 Corinthians 13:4', text: 'Love is patient, love is kind. It does not envy, it does not boast, it is not proud.' },
  { reference: 'Psalm 27:1', text: 'The Lord is my light and my salvation—whom shall I fear? The Lord is the stronghold of my life—of whom shall I be afraid?' },
  { reference: 'Isaiah 40:31', text: 'But those who hope in the Lord will renew their strength. They will soar on wings like eagles.' },
  { reference: 'John 15:5', text: 'I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit.' },
  { reference: 'Philippians 4:6', text: 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.' },
  { reference: 'Romans 8:38', text: 'For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God.' },
  { reference: 'Psalm 34:18', text: 'The Lord is close to the brokenhearted and saves those who are crushed in spirit.' },
  { reference: 'Lamentations 3:22', text: 'Because of the Lord\'s great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness.' },
  { reference: 'Hebrews 11:1', text: 'Now faith is confidence in what we hope for and assurance about what we do not see.' },
  { reference: 'Proverbs 16:3', text: 'Commit to the Lord whatever you do, and he will establish your plans.' },
  { reference: 'Matthew 5:6', text: 'Blessed are those who hunger and thirst for righteousness, for they will be filled.' },
  { reference: '1 Peter 5:7', text: 'Cast all your anxiety on him because he cares for you.' },
  { reference: 'Psalm 91:1', text: 'Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty.' },
  { reference: 'John 10:10', text: 'The thief comes only to steal and kill and destroy; I have come that they may have life, and have it to the full.' },
  { reference: 'Colossians 3:23', text: 'Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.' },
  { reference: 'Romans 15:13', text: 'May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope by the power of the Holy Spirit.' },
  { reference: 'Psalm 37:4', text: 'Take delight in the Lord, and he will give you the desires of your heart.' },
  { reference: 'Isaiah 43:2', text: 'When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you.' },
  { reference: 'James 1:2', text: 'Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds.' },
  { reference: 'John 16:33', text: 'I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world.' },
  { reference: 'Psalm 9:10', text: 'Those who know your name trust in you, for you, Lord, have never forsaken those who seek you.' },
  { reference: 'Proverbs 4:23', text: 'Above all else, guard your heart, for everything you do flows from it.' },
  { reference: 'Romans 10:9', text: 'If you declare with your mouth, Jesus is Lord, and believe in your heart that God raised him from the dead, you will be saved.' },
  { reference: 'Luke 11:9', text: 'So I say to you: Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.' },
  { reference: 'Psalm 143:10', text: 'Teach me to do your will, for you are my God; may your good Spirit lead me on level ground.' },
  { reference: '2 Chronicles 7:14', text: 'If my people, who are called by my name, will humble themselves and pray and seek my face and turn from their wicked ways, then I will hear from heaven, and I will forgive their sin and will heal their land.' },
  { reference: 'Micah 6:8', text: 'He has shown you, O mortal, what is good. And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God.' },
  { reference: 'Ephesians 4:32', text: 'Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.' },
  { reference: 'Psalm 100:4', text: 'Enter his gates with thanksgiving and his courts with praise; give thanks to him and praise his name.' },
  { reference: 'Deuteronomy 31:6', text: 'Be strong and courageous. Do not be afraid or terrified because of them, for the Lord your God goes with you.' },
  { reference: '1 John 4:19', text: 'We love because he first loved us.' },
  { reference: 'Proverbs 31:25', text: 'She is clothed with strength and dignity; she can laugh at the days to come.' },
  { reference: 'Genesis 1:1', text: 'In the beginning God created the heavens and the earth.' },
  { reference: 'John 1:1', text: 'In the beginning was the Word, and the Word was with God, and the Word was God.' },
  { reference: 'Matthew 28:20', text: 'And surely I am with you always, to the very end of the age.' },
  { reference: 'Psalm 150:6', text: 'Let everything that has breath praise the Lord. Praise the Lord.' },
  { reference: 'Romans 6:23', text: 'For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.' },
  { reference: 'John 11:25', text: 'Jesus said to her, I am the resurrection and the life. The one who believes in me will live, even though they die.' },
  { reference: 'Psalm 121:1', text: 'I lift up my eyes to the mountains—where does my help come from? My help comes from the Lord, the Maker of heaven and earth.' },
  { reference: 'Acts 2:38', text: 'Peter replied, Repent and be baptized, every one of you, in the name of Jesus Christ for the forgiveness of your sins. And you will receive the gift of the Holy Spirit.' },
  { reference: 'Philippians 2:3', text: 'Do nothing out of selfish ambition or vain conceit. Rather, in humility value others above yourselves.' },
  { reference: 'Hebrews 4:12', text: 'For the word of God is alive and active. Sharper than any double-edged sword, it penetrates even to dividing soul and spirit.' },
  { reference: 'Isaiah 26:3', text: 'You will keep in perfect peace those whose minds are steadfast, because they trust in you.' },
  { reference: 'Psalm 51:10', text: 'Create in me a pure heart, O God, and renew a steadfast spirit within me.' },
  { reference: 'John 8:32', text: 'Then you will know the truth, and the truth will set you free.' },
  { reference: '2 Corinthians 5:17', text: 'Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!' },
  { reference: 'Matthew 5:9', text: 'Blessed are the peacemakers, for they will be called children of God.' },
  { reference: 'Proverbs 11:14', text: 'For lack of guidance a nation falls, but victory is won through many advisers.' },
  { reference: 'Psalm 139:14', text: 'I praise you because I am fearfully and wonderfully made; your works are wonderful, I know that full well.' },
  { reference: 'John 3:30', text: 'He must become greater; I must become less.' },
  { reference: 'Acts 1:8', text: 'But you will receive power when the Holy Spirit comes on you; and you will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth.' },
  { reference: 'Romans 8:1', text: 'Therefore, there is now no condemnation for those who are in Christ Jesus.' },
  { reference: 'Colossians 1:17', text: 'He is before all things, and in him all things hold together.' },
  { reference: 'Matthew 5:14', text: 'You are the light of the world. A town built on a hill cannot be hidden.' },
  { reference: 'Psalm 46:10', text: 'He says, Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth.' },
  { reference: 'Isaiah 55:8', text: '"For my thoughts are not your thoughts, neither are your ways my ways," declares the Lord.' },
  { reference: 'John 6:35', text: 'Then Jesus declared, I am the bread of life. Whoever comes to me will never go hungry, and whoever believes in me will never be thirsty.' },
  { reference: 'Galatians 5:22', text: 'But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control.' },
  { reference: '1 Thessalonians 5:18', text: 'Give thanks in all circumstances; for this is God\'s will for you in Christ Jesus.' },
  { reference: 'Psalm 86:5', text: 'You, Lord, are forgiving and good, abounding in love to all who call to you.' },
  { reference: 'John 13:34', text: 'A new command I give you: Love one another. As I have loved you, so you must love one another.' },
  { reference: 'Romans 12:19', text: 'Do not take revenge, my dear friends, but leave room for God\'s wrath, for it is written: It is mine to avenge; I will repay, says the Lord.' },
  { reference: 'Matthew 6:9', text: 'Our Father in heaven, hallowed be your name, your kingdom come, your will be done, on earth as it is in heaven.' },
  { reference: '1 Corinthians 10:13', text: 'No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear.' },
  { reference: 'Psalm 25:4', text: 'Show me your ways, Lord, teach me your paths.' },
  { reference: 'Hebrews 10:23', text: 'Let us hold unswervingly to the hope we profess, for he who promised is faithful.' },
  { reference: 'Luke 1:37', text: 'For no word from God will ever fail.' },
  { reference: 'Psalm 32:8', text: 'I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.' },
  { reference: 'Ephesians 6:10', text: 'Finally, be strong in the Lord and in his mighty power.' },
  { reference: 'John 14:27', text: 'Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.' },
  { reference: 'Proverbs 18:10', text: 'The name of the Lord is a fortified tower; the righteous run to it and are safe.' },
  { reference: 'Romans 8:31', text: 'What, then, shall we say in response to these things? If God is for us, who can be against us?' },
  { reference: 'Psalm 73:26', text: 'My flesh and my heart may fail, but God is the strength of my heart and my portion forever.' },
  { reference: 'Matthew 5:3', text: 'Blessed are the poor in spirit, for theirs is the kingdom of heaven.' },
  { reference: '2 Timothy 1:7', text: 'For God has not given us a spirit of fear, but of power and of love and of a sound mind.' },
  { reference: 'Isaiah 48:17', text: 'I am the Lord your God, who teaches you what is best for you, who directs you in the way you should go.' },
  { reference: 'John 4:24', text: 'God is spirit, and his worshipers must worship in the Spirit and in truth.' },
  { reference: 'Psalm 16:8', text: 'I keep my eyes always on the Lord. With him at my right hand, I will not be shaken.' },
  { reference: 'James 4:7', text: 'Submit yourselves, then, to God. Resist the devil, and he will flee from you.' },
  { reference: 'Colossians 3:2', text: 'Set your minds on things above, not on earthly things.' },
  { reference: 'Psalm 55:22', text: 'Cast your cares on the Lord and he will sustain you; he will never let the righteous be shaken.' },
  { reference: 'Luke 6:27', text: 'But to you who are listening I say: Love your enemies, do good to those who hate you.' },
  { reference: 'Romans 1:16', text: 'For I am not ashamed of the gospel, because it is the power of God that brings salvation to everyone who believes.' },
  { reference: 'Psalm 3:3', text: 'But you, Lord, are a shield around me, my glory, the One who lifts my head high.' },
  { reference: 'John 15:13', text: 'Greater love has no one than this: to lay down one\'s life for one\'s friends.' },
  { reference: 'Ephesians 3:20', text: 'Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us.' },
  { reference: 'Proverbs 22:6', text: 'Start children off on the way they should go, and even when they are old they will not turn from it.' },
  { reference: 'Isaiah 58:11', text: 'The Lord will guide you always; he will satisfy your needs in a sun-scorched land.' },
  { reference: 'Psalm 40:2', text: 'He lifted me out of the slimy pit, out of the mud and mire; he set my feet on a rock and gave me a firm place to stand.' },
  { reference: 'Matthew 7:7', text: 'Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.' },
  { reference: '1 John 1:9', text: 'If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.' },
  { reference: 'Acts 4:12', text: 'Salvation is found in no one else, for there is no other name under heaven given to mankind by which we must be saved.' },
  { reference: 'Psalm 130:7', text: 'Israel, put your hope in the Lord, for with the Lord is unfailing love and with him is full redemption.' },
  { reference: 'Hebrews 13:8', text: 'Jesus Christ is the same yesterday and today and forever.' },
  { reference: 'Matthew 5:16', text: 'In the same way, let your light shine before others, that they may see your good deeds and glorify your Father in heaven.' },
  { reference: 'Proverbs 3:6', text: 'In all your ways submit to him, and he will make your paths straight.' },
  { reference: 'Romans 12:12', text: 'Be joyful in hope, patient in affliction, faithful in prayer.' },
  { reference: 'John 8:12', text: 'When Jesus spoke again to the people, he said, I am the light of the world. Whoever follows me will never walk in darkness, but will have the light of life.' },
  { reference: 'Psalm 34:8', text: 'Taste and see that the Lord is good; blessed is the one who takes refuge in him.' },
  { reference: '2 Corinthians 12:9', text: 'But he said to me, My grace is sufficient for you, for my power is made perfect in weakness.' },
  { reference: 'Psalm 147:3', text: 'He heals the brokenhearted and binds up their wounds.' },
  { reference: 'Isaiah 40:28', text: 'The Lord is the everlasting God, the Creator of the ends of the earth. He will not grow tired or weary.' },
  { reference: 'Luke 17:21', text: 'The kingdom of God is in your midst.' },
  { reference: 'Romans 8:17', text: 'Now if we are children, then we are heirs—heirs of God and co-heirs with Christ.' },
  { reference: 'Psalm 68:19', text: 'Praise be to the Lord, to God our Savior, who daily bears our burdens.' },
  { reference: 'Matthew 19:26', text: 'With man this is impossible, but with God all things are possible.' },
  { reference: 'James 1:17', text: 'Every good and perfect gift is from above, coming down from the Father of the heavenly lights.' },
  { reference: 'John 20:29', text: 'Then Jesus told him, Because you have seen me, you have believed; blessed are those who have not seen and yet have believed.' },
  { reference: 'Ephesians 1:7', text: 'In him we have redemption through his blood, the forgiveness of sins, in accordance with the riches of God\'s grace.' },
  { reference: 'Psalm 119:11', text: 'I have hidden your word in my heart that I might not sin against you.' },
  { reference: '1 John 4:4', text: 'You, dear children, are from God and have overcome them, because the one who is in you is greater than the one who is in the world.' },
  { reference: 'Proverbs 17:17', text: 'A friend loves at all times, and a brother is born for a time of adversity.' },
  { reference: 'Isaiah 54:10', text: '"Though the mountains be shaken and the hills be removed, yet my unfailing love for you will not be shaken," says the Lord.' },
  { reference: 'Romans 5:1', text: 'Therefore, since we have been justified through faith, we have peace with God through our Lord Jesus Christ.' },
  { reference: 'Psalm 145:18', text: 'The Lord is near to all who call on him, to all who call on him in truth.' },
  { reference: 'Matthew 6:25', text: 'Therefore I tell you, do not worry about your life, what you will eat or drink; or about your body, what you will wear.' },
  { reference: '2 Peter 1:3', text: 'His divine power has given us everything we need for a godly life through our knowledge of him who called us by his own glory and goodness.' },
  { reference: 'John 17:17', text: 'Sanctify them by the truth; your word is truth.' },
  { reference: 'Psalm 30:5', text: 'Weeping may stay for the night, but rejoicing comes in the morning.' },
  { reference: 'Colossians 4:6', text: 'Let your conversation be always full of grace, seasoned with salt, so that you may know how to answer everyone.' },
  { reference: 'Hebrews 12:2', text: 'Fixing our eyes on Jesus, the pioneer and perfecter of faith.' },
  { reference: 'Isaiah 61:1', text: 'The Spirit of the Sovereign Lord is on me, because the Lord has anointed me to proclaim good news to the poor.' },
  { reference: 'Romans 12:1', text: 'Therefore, I urge you, brothers and sisters, in view of God\'s mercy, to offer your bodies as a living sacrifice, holy and pleasing to God.' },
  { reference: 'Psalm 19:1', text: 'The heavens declare the glory of God; the skies proclaim the work of his hands.' },
  { reference: 'Matthew 22:37', text: 'Jesus replied: Love the Lord your God with all your heart and with all your soul and with all your mind.' },
  { reference: 'Philippians 4:4', text: 'Rejoice in the Lord always. I will say it again: Rejoice!' },
  { reference: 'John 7:38', text: 'Whoever believes in me, as Scripture has said, rivers of living water will flow from within them.' },
  { reference: 'Proverbs 10:22', text: 'The blessing of the Lord brings wealth, without painful toil for it.' },
  { reference: '1 Corinthians 13:13', text: 'And now these three remain: faith, hope and love. But the greatest of these is love.' },
  { reference: 'Psalm 62:8', text: 'Trust in him at all times, you people; pour out your hearts to him, for God is our refuge.' },
  { reference: 'Isaiah 43:25', text: 'I, even I, am he who blots out your transgressions, for my own sake, and remembers your sins no more.' },
  { reference: 'Revelation 21:4', text: 'He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain.' },
  { reference: 'Luke 12:7', text: 'Indeed, the very hairs of your head are all numbered. Don\'t be afraid; you are worth more than many sparrows.' },
  { reference: 'Romans 8:5', text: 'Those who live according to the flesh have their minds set on what the flesh desires; but those who live in accordance with the Spirit have their minds set on what the Spirit desires.' },
  { reference: 'Psalm 29:11', text: 'The Lord gives strength to his people; the Lord blesses his people with peace.' },
  { reference: 'James 5:16', text: 'Therefore confess your sins to each other and pray for each other so that you may be healed. The prayer of a righteous person is powerful and effective.' },
  { reference: 'John 15:7', text: 'If you remain in me and my words remain in you, ask whatever you wish, and it will be done for you.' },
  { reference: 'Ephesians 5:19', text: 'Speaking to one another with psalms, hymns, and songs from the Spirit. Sing and make music from your heart to the Lord.' },
  { reference: 'Psalm 18:2', text: 'The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge.' },
  { reference: 'Matthew 5:8', text: 'Blessed are the pure in heart, for they will see God.' },
  { reference: 'Isaiah 40:4', text: 'Every valley shall be raised up, every mountain and hill made low; the rough ground shall become level, the rugged places a plain.' },
  { reference: 'Acts 20:24', text: 'However, I consider my life worth nothing to me; my only aim is to finish the race and complete the task the Lord Jesus has given me.' },
  { reference: '1 John 3:1', text: 'See what great love the Father has lavished on us, that we should be called children of God! And that is what we are!' },
  { reference: 'Psalm 41:3', text: 'The Lord sustains them on their sickbed and restores them from their bed of illness.' },
  { reference: 'Romans 13:14', text: 'Rather, clothe yourselves with the Lord Jesus Christ, and do not think about how to gratify the desires of the flesh.' },
  { reference: 'Proverbs 28:1', text: 'The wicked flee though no one pursues, but the righteous are as bold as a lion.' },
  { reference: 'John 14:1', text: 'Do not let your hearts be troubled. You believe in God; believe also in me.' },
  { reference: 'Luke 4:18', text: 'The Spirit of the Lord is on me, because he has anointed me to proclaim good news to the poor.' },
  { reference: 'Psalm 126:3', text: 'The Lord has done great things for us, and we are filled with joy.' },
  { reference: '2 Corinthians 9:8', text: 'And God is able to bless you abundantly, so that in all things at all times, having all that you need, you will abound in every good work.' },
  { reference: 'Ephesians 2:10', text: 'For we are God\'s handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.' },
  { reference: 'Matthew 11:29', text: 'Take my yoke upon you and learn from me, for I am gentle and humble in heart, and you will find rest for your souls.' },
  { reference: 'Psalm 18:30', text: 'As for God, his way is perfect: The Lord\'s word is flawless; he shields all who take refuge in him.' },
  { reference: 'Romans 4:21', text: 'Being fully persuaded that God had power to do what he had promised.' },
  { reference: 'Isaiah 60:1', text: 'Arise, shine, for your light has come, and the glory of the Lord rises upon you.' },
  { reference: 'John 4:14', text: 'But whoever drinks the water I give them will never thirst. Indeed, the water I give them will become in them a spring of water welling up to eternal life.' },
  { reference: 'Hebrews 6:19', text: 'We have this hope as an anchor for the soul, firm and secure.' },
  { reference: 'Psalm 119:165', text: 'Great peace have those who love your law, and nothing can make them stumble.' },
  { reference: 'Matthew 6:34', text: 'Therefore do not worry about tomorrow, for tomorrow will worry about itself.' },
  { reference: 'Acts 16:31', text: 'They replied, Believe in the Lord Jesus, and you will be saved—you and your household.' },
  { reference: 'Psalm 103:12', text: 'As far as the east is from the west, so far has he removed our transgressions from us.' },
  { reference: 'Philippians 1:6', text: 'Being confident of this, that he who began a good work in you will carry it on to completion until the day of Christ Jesus.' },
  { reference: '1 John 5:14', text: 'This is the confidence we have in approaching God: that if we ask anything according to his will, he hears us.' },
  { reference: 'Proverbs 14:12', text: 'There is a way that appears to be right, but in the end it leads to death.' },
  { reference: 'Isaiah 41:13', text: 'For I am the Lord your God who takes hold of your right hand and says to you, Do not fear; I will help you.' },
  { reference: 'Luke 18:27', text: 'Jesus replied, What is impossible with man is possible with God.' },
  { reference: 'Romans 12:21', text: 'Do not be overcome by evil, but overcome evil with good.' },
  { reference: 'Psalm 56:3', text: 'When I am afraid, I put my trust in you.' },
  { reference: 'John 14:16', text: 'And I will ask the Father, and he will give you another advocate to help you and be with you forever—the Spirit of truth.' },
  { reference: 'Colossians 2:6', text: 'So then, just as you received Christ Jesus as Lord, continue to live your lives in him.' },
  { reference: 'Matthew 5:10', text: 'Blessed are those who are persecuted because of righteousness, for theirs is the kingdom of heaven.' },
  { reference: 'Ephesians 6:18', text: 'And pray in the Spirit on all occasions with all kinds of prayers and requests.' },
  { reference: 'Psalm 27:14', text: 'Wait for the Lord; be strong and take heart and wait for the Lord.' },
  { reference: 'Romans 12:10', text: 'Be devoted to one another in love. Honor one another above yourselves.' },
  { reference: 'Isaiah 43:1', text: 'But now, this is what the Lord says—he who created you, Jacob, he who formed you, Israel: Do not fear, for I have redeemed you; I have summoned you by name; you are mine.' },
  { reference: 'Hebrews 11:6', text: 'And without faith it is impossible to please God, because anyone who comes to him must believe that he exists and that he rewards those who earnestly seek him.' },
  { reference: 'Psalm 7:17', text: 'I will give thanks to the Lord because of his righteousness; I will sing the praises of the name of the Lord Most High.' },
  { reference: 'John 6:48', text: 'I am the bread of life.' },
  { reference: 'Romans 3:23', text: 'For all have sinned and fall short of the glory of God.' },
  { reference: 'Proverbs 19:21', text: 'Many are the plans in a person\'s heart, but it is the Lord\'s purpose that prevails.' },
  { reference: 'Luke 10:27', text: 'Love the Lord your God with all your heart and with all your soul and with all your strength and with all your mind; and love your neighbor as yourself.' },
  { reference: '2 Corinthians 4:17', text: 'For our light and momentary troubles are achieving for us an eternal glory that far outweighs them all.' },
  { reference: 'Psalm 97:12', text: 'Rejoice in the Lord, you who are righteous, and praise his holy name.' },
  { reference: 'Matthew 6:12', text: 'Forgive us our debts, as we also have forgiven our debtors.' },
  { reference: 'Ephesians 4:2', text: 'Be completely humble and gentle; be patient, bearing with one another in love.' },
  { reference: 'Isaiah 25:1', text: 'Lord, you are my God; I will exalt you and praise your name, for in perfect faithfulness you have done wonderful things.' },
  { reference: 'Romans 8:26', text: 'The Spirit helps us in our weakness. We do not know what we ought to pray for, but the Spirit himself intercedes for us through wordless groans.' },
  { reference: 'Psalm 143:1', text: 'Lord, hear my prayer, listen to my cry for mercy; in your faithfulness and righteousness come to my relief.' },
  { reference: 'John 15:16', text: 'You did not choose me, but I chose you and appointed you so that you might go and bear fruit—fruit that will last.' },
  { reference: 'James 1:22', text: 'Do not merely listen to the word, and so deceive yourselves. Do what it says.' },
  { reference: '1 Peter 1:3', text: 'Praise be to the God and Father of our Lord Jesus Christ! In his great mercy he has given us new birth into a living hope.' },
  { reference: 'Psalm 139:1', text: 'You have searched me, Lord, and you know me.' },
  { reference: 'Matthew 7:12', text: 'So in everything, do to others what you would have them do to you, for this sums up the Law and the Prophets.' },
  { reference: 'Philippians 3:14', text: 'I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus.' },
  { reference: 'Romans 11:36', text: 'For from him and through him and for him are all things. To him be the glory forever! Amen.' },
  { reference: 'Isaiah 30:21', text: 'Whether you turn to the right or to the left, your ears will hear a voice behind you, saying, This is the way; walk in it.' },
  { reference: 'Psalm 108:4', text: 'For great is your love, higher than the heavens; your faithfulness reaches to the skies.' },
  { reference: 'Colossians 1:16', text: 'For in him all things were created: things in heaven and on earth, visible and invisible.' },
  { reference: 'John 3:3', text: 'Jesus replied, Very truly I tell you, no one can see the kingdom of God unless they are born again.' },
  { reference: 'Hebrews 9:28', text: 'So Christ was sacrificed once to take away the sins of many; and he will appear a second time, not to bear sin, but to bring salvation to those who are waiting for him.' },
  { reference: 'Proverbs 12:25', text: 'Anxiety weighs down the heart, but a kind word cheers it up.' },
  { reference: '1 Corinthians 3:16', text: 'Don\'t you know that you yourselves are God\'s temple and that God\'s Spirit dwells in your midst?' },
  { reference: 'Psalm 116:1', text: 'I love the Lord, for he heard my voice; he heard my cry for mercy.' },
  { reference: 'Isaiah 26:4', text: 'Trust in the Lord forever, for the Lord, the Lord himself, is the Rock eternal.' },
  { reference: 'Luke 15:7', text: 'I tell you that in the same way there will be more rejoicing in heaven over one sinner who repents than over ninety-nine righteous persons who do not need to repent.' },
  { reference: 'Romans 8:39', text: 'Neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord.' },
  { reference: 'Matthew 18:20', text: 'For where two or three gather in my name, there am I with them.' },
  { reference: 'Psalm 34:1', text: 'I will extol the Lord at all times; his praise will always be on my lips.' },
  { reference: 'John 10:27', text: 'My sheep listen to my voice; I know them, and they follow me.' },
  { reference: 'Ephesians 5:2', text: 'And walk in the way of love, just as Christ loved us and gave himself up for us as a fragrant offering and sacrifice to God.' },
  { reference: 'Isaiah 44:6', text: 'This is what the Lord says—Israel\'s King and Redeemer, the Lord Almighty: I am the first and I am the last; apart from me there is no God.' },
  { reference: '2 Corinthians 3:17', text: 'Now the Lord is the Spirit, and where the Spirit of the Lord is, there is freedom.' },
  { reference: 'Psalm 119:9', text: 'How can a young person stay on the path of purity? By living according to your word.' },
  { reference: 'Matthew 5:5', text: 'Blessed are the meek, for they will inherit the earth.' },
  { reference: 'Romans 12:15', text: 'Rejoice with those who rejoice; mourn with those who mourn.' },
  { reference: 'John 11:35', text: 'Jesus wept.' },
  { reference: 'Proverbs 15:3', text: 'The eyes of the Lord are everywhere, keeping watch on the wicked and the good.' },
  { reference: 'Hebrews 13:5', text: 'Never will I leave you; never will I forsake you.' },
  { reference: 'Psalm 103:2', text: 'Praise the Lord, my soul, and forget not all his benefits.' },
  { reference: 'Acts 2:42', text: 'They devoted themselves to the apostles\' teaching and to fellowship, to the breaking of bread and to prayer.' },
  { reference: 'Luke 19:10', text: 'For the Son of Man came to seek and to save the lost.' },
  { reference: 'Revelation 3:20', text: 'Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with that person, and they with me.' },
  { reference: 'Psalm 5:3', text: 'In the morning, Lord, you hear my voice; in the morning I lay my requests before you and wait expectantly.' },
  { reference: 'Isaiah 53:5', text: 'But he was pierced for our transgressions, he was crushed for our iniquities; the punishment that brought us peace was on him, and by his wounds we are healed.' },
  { reference: 'Matthew 24:35', text: 'Heaven and earth will pass away, but my words will never pass away.' },
  { reference: 'Romans 12:4', text: 'For just as each of us has one body with many members, and these members do not all have the same function.' },
  { reference: '1 John 2:17', text: 'The world and its desires pass away, but whoever does the will of God lives forever.' },
  { reference: 'Psalm 63:1', text: 'You, God, are my God, earnestly I seek you; I thirst for you, my whole being longs for you.' },
  { reference: 'John 16:24', text: 'Until now you have not asked for anything in my name. Ask and you will receive, and your joy will be complete.' },
  { reference: 'Philippians 4:19', text: 'And my God will meet all your needs according to the riches of his glory in Christ Jesus.' },
  { reference: 'Galatians 6:9', text: 'Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.' },
  { reference: 'Psalm 111:10', text: 'The fear of the Lord is the beginning of wisdom; all who follow his precepts have good understanding.' },
  { reference: 'Colossians 3:16', text: 'Let the message of Christ dwell among you richly as you teach and admonish one another with all wisdom through psalms, hymns, and songs from the Spirit.' },
  { reference: 'Matthew 5:7', text: 'Blessed are the merciful, for they will be shown mercy.' },
  { reference: 'Isaiah 40:10', text: 'See, the Sovereign Lord comes with power, and he rules with a mighty arm.' },
  { reference: 'Romans 9:16', text: 'It does not, therefore, depend on human desire or effort, but on God\'s mercy.' },
  { reference: 'Psalm 18:35', text: 'You make your saving help my shield, and your right hand sustains me; your help has made me great.' },
  { reference: 'John 5:24', text: 'Very truly I tell you, whoever hears my word and believes him who sent me has eternal life and will not be judged but has crossed over from death to life.' },
  { reference: 'James 1:25', text: 'But whoever looks intently into the perfect law that gives freedom, and continues in it—not forgetting what they have heard, but doing it—they will be blessed in what they do.' },
  { reference: '2 Corinthians 6:2', text: 'I tell you, now is the time of God\'s favor, now is the day of salvation.' },
  { reference: 'Psalm 4:8', text: 'In peace I will lie down and sleep, for you alone, Lord, make me dwell in safety.' },
  { reference: 'Luke 23:34', text: 'Jesus said, Father, forgive them, for they do not know what they are doing.' },
  { reference: 'Ephesians 2:14', text: 'For he himself is our peace, who has made the two groups one and has destroyed the barrier, the dividing wall of hostility.' },
  { reference: 'Matthew 25:40', text: 'The King will reply, Truly I tell you, whatever you did for one of the least of these brothers and sisters of mine, you did for me.' },
  { reference: 'Romans 5:3', text: 'We also glory in our sufferings, because we know that suffering produces perseverance.' },
  { reference: 'Psalm 89:1', text: 'I will sing of the Lord\'s great love forever; with my mouth I will make your faithfulness known through all generations.' },
  { reference: 'John 14:3', text: 'And if I go and prepare a place for you, I will come back and take you to be with me that you also may be where I am.' },
  { reference: 'Proverbs 27:1', text: 'Do not boast about tomorrow, for you do not know what a day may bring.' },
  { reference: 'Isaiah 55:11', text: 'So is my word that goes out from my mouth: It will not return to me empty, but will accomplish what I desire and achieve the purpose for which I sent it.' },
  { reference: '1 Peter 4:8', text: 'Above all, love each other deeply, because love covers over a multitude of sins.' },
  { reference: 'Psalm 37:5', text: 'Commit your way to the Lord; trust in him and he will do this.' },
  { reference: 'Hebrews 4:16', text: 'Let us then approach God\'s throne of grace with confidence, so that we may receive mercy and find grace to help us in our time of need.' },
  { reference: 'John 12:46', text: 'I have come into the world as a light, so that no one who believes in me should stay in darkness.' },
  { reference: 'Matthew 5:4', text: 'Blessed are those who mourn, for they will be comforted.' },
  { reference: 'Romans 6:4', text: 'We were therefore buried with him through baptism into death in order that, just as Christ was raised from the dead through the glory of the Father, we too may live a new life.' },
  { reference: 'Psalm 93:2', text: 'Your throne was established long ago; you are from all eternity.' },
  { reference: 'Colossians 1:27', text: 'Christ in you, the hope of glory.' },
  { reference: '1 Corinthians 15:58', text: 'Therefore, my dear brothers and sisters, stand firm. Let nothing move you. Always give yourselves fully to the work of the Lord.' },
  { reference: 'Isaiah 40:8', text: 'The grass withers and the flowers fall, but the word of our God endures forever.' },
  { reference: 'Luke 21:33', text: 'Heaven and earth will pass away, but my words will never pass away.' },
  { reference: 'Psalm 24:1', text: 'The earth is the Lord\'s, and everything in it, the world, and all who live in it.' },
  { reference: 'John 6:63', text: 'The Spirit gives life; the flesh counts for nothing. The words I have spoken to you—they are full of the Spirit and life.' },
  { reference: 'Ephesians 1:17', text: 'I keep asking that the God of our Lord Jesus Christ, the glorious Father, may give you the Spirit of wisdom and revelation, so that you may know him better.' },
  { reference: 'Romans 8:37', text: 'No, in all these things we are more than conquerors through him who loved us.' },
  { reference: 'Proverbs 24:16', text: 'For though the righteous fall seven times, they rise again, but the wicked stumble when calamity strikes.' },
  { reference: 'Matthew 11:30', text: 'For my yoke is easy and my burden is light.' },
  { reference: 'Psalm 33:20', text: 'We wait in hope for the Lord; he is our help and our shield.' },
  { reference: '2 Timothy 4:7', text: 'I have fought the good fight, I have finished the race, I have kept the faith.' },
  { reference: 'John 14:13', text: 'And I will do whatever you ask in my name, so that the Father may be glorified in the Son.' },
  { reference: 'Isaiah 64:8', text: 'Yet you, Lord, are our Father. We are the clay, you are the potter; we are all the work of your hand.' },
  { reference: 'Acts 17:28', text: 'For in him we live and move and have our being.' },
  { reference: 'Psalm 46:7', text: 'The Lord Almighty is with us; the God of Jacob is our fortress.' },
  { reference: 'Revelation 22:13', text: 'I am the Alpha and the Omega, the First and the Last, the Beginning and the End.' },
  { reference: 'Romans 5:5', text: 'And hope does not put us to shame, because God\'s love has been poured out into our hearts through the Holy Spirit, who has been given to us.' },
  { reference: 'Psalm 86:15', text: 'But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love and faithfulness.' },
  { reference: 'Matthew 4:4', text: 'Man shall not live on bread alone, but on every word that comes from the mouth of God.' },
  { reference: 'John 15:11', text: 'I have told you this so that my joy may be in you and that your joy may be complete.' },
  { reference: 'Philippians 4:7', text: 'And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.' },
  { reference: 'Psalm 119:130', text: 'The unfolding of your words gives light; it gives understanding to the simple.' },
  { reference: '1 John 3:18', text: 'Dear children, let us not love with words or speech but with actions and in truth.' },
  { reference: 'Isaiah 40:29', text: 'He gives strength to the weary and increases the power of the weak.' },
  { reference: 'Hebrews 1:3', text: 'The Son is the radiance of God\'s glory and the exact representation of his being.' },
  { reference: 'Luke 6:38', text: 'Give, and it will be given to you. A good measure, pressed down, shaken together and running over, will be poured into your lap.' },
  { reference: 'Psalm 28:7', text: 'The Lord is my strength and my shield; my heart trusts in him, and he helps me.' },
  { reference: 'Romans 12:9', text: 'Love must be sincere. Hate what is evil; cling to what is good.' },
  { reference: 'John 10:30', text: 'I and the Father are one.' },
  { reference: 'Colossians 3:14', text: 'And over all these virtues put on love, which binds them all together in perfect unity.' },
  { reference: 'Matthew 5:11', text: 'Blessed are you when people insult you, persecute you and falsely say all kinds of evil against you because of me.' },
  { reference: 'Psalm 103:17', text: 'But from everlasting to everlasting the Lord\'s love is with those who fear him.' },
  { reference: 'Isaiah 43:18', text: 'Forget the former things; do not dwell on the past.' },
  { reference: '1 Peter 2:9', text: 'But you are a chosen people, a royal priesthood, a holy nation, God\'s special possession.' },
  { reference: 'John 3:36', text: 'Whoever believes in the Son has eternal life, but whoever rejects the Son will not see life.' },
  { reference: 'Acts 2:21', text: 'And everyone who calls on the name of the Lord will be saved.' },
  { reference: 'Psalm 91:11', text: 'For he will command his angels concerning you to guard you in all your ways.' },
  { reference: 'Romans 8:24', text: 'For in this hope we were saved. But hope that is seen is no hope at all.' },
  { reference: 'Proverbs 3:7', text: 'Do not be wise in your own eyes; fear the Lord and shun evil.' },
  { reference: 'Matthew 5:12', text: 'Rejoice and be glad, because great is your reward in heaven.' },
  { reference: 'Ephesians 3:17', text: 'So that Christ may dwell in your hearts through faith. And I pray that you, being rooted and established in love.' },
  { reference: 'Psalm 17:8', text: 'Keep me as the apple of your eye; hide me in the shadow of your wings.' },
  { reference: 'John 8:36', text: 'So if the Son sets you free, you will be free indeed.' },
  { reference: 'Isaiah 66:2', text: 'These are the ones I look on with favor: those who are humble and contrite in spirit, and who tremble at my word.' },
  { reference: 'Luke 9:23', text: 'Whoever wants to be my disciple must deny themselves and take up their cross daily and follow me.' },
  { reference: 'Romans 7:25', text: 'Thanks be to God, who delivers me through Jesus Christ our Lord!' },
  { reference: 'Psalm 84:11', text: 'For the Lord God is a sun and shield; the Lord bestows favor and honor; no good thing does he withhold from those whose walk is blameless.' },
  { reference: '2 Corinthians 1:3', text: 'Praise be to the God and Father of our Lord Jesus Christ, the Father of compassion and the God of all comfort.' },
  { reference: 'Hebrews 12:1', text: 'Therefore, since we are surrounded by such a great cloud of witnesses, let us throw off everything that hinders and the sin that so easily entangles.' },
  { reference: 'Matthew 6:10', text: 'Your kingdom come, your will be done, on earth as it is in heaven.' },
  { reference: 'Psalm 18:6', text: 'In my distress I called to the Lord; I cried to my God for help.' },
  { reference: 'John 15:4', text: 'Remain in me, as I also remain in you. No branch can bear fruit by itself; it must remain in the vine.' },
  { reference: 'Philippians 4:11', text: 'I have learned, in whatsoever state I am, therewith to be content.' },
  { reference: 'Isaiah 28:16', text: 'So this is what the Sovereign Lord says: See, I lay a stone in Zion, a tested stone, a precious cornerstone for a sure foundation.' },
  { reference: 'Romans 10:17', text: 'Consequently, faith comes from hearing the message, and the message is heard through the word about Christ.' },
  { reference: 'Psalm 107:1', text: 'Give thanks to the Lord, for he is good; his love endures forever.' },
  { reference: 'John 3:17', text: 'For God did not send his Son into the world to condemn the world, but to save the world through him.' },
  { reference: 'Colossians 3:17', text: 'And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through him.' },
  { reference: 'Matthew 28:19', text: 'Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit.' },
  { reference: 'Psalm 139:23', text: 'Search me, God, and know my heart; test me and know my anxious thoughts.' },
  { reference: 'Hebrews 10:25', text: 'Not giving up meeting together, as some are in the habit of doing, but encouraging one another—and all the more as you see the Day approaching.' },
  { reference: 'John 14:23', text: 'Jesus replied, Anyone who loves me will obey my teaching. My Father will love them, and we will come to them and make our home with them.' },
  { reference: '1 Corinthians 6:19', text: 'Do you not know that your bodies are temples of the Holy Spirit, who is in you, whom you have received from God? You are not your own.' },
  { reference: 'Psalm 136:26', text: 'Give thanks to the God of heaven. His love endures forever.' },
  { reference: 'Romans 14:17', text: 'For the kingdom of God is not a matter of eating and drinking, but of righteousness, peace and joy in the Holy Spirit.' },
  { reference: 'Isaiah 55:1', text: 'Come, all you who are thirsty, come to the waters; and you who have no money, come, buy and eat!' },
  { reference: 'Luke 1:49', text: 'For the Mighty One has done great things for me—holy is his name.' },
  { reference: 'Matthew 16:18', text: 'And I tell you that you are Peter, and on this rock I will build my church, and the gates of Hades will not overcome it.' },
  { reference: 'Ephesians 4:29', text: 'Do not let any unwholesome talk come out of your mouths, but only what is helpful for building others up according to their needs.' },
  { reference: 'Psalm 145:8', text: 'The Lord is gracious and compassionate, slow to anger and rich in love.' },
  { reference: 'John 6:68', text: 'Simon Peter answered him, Lord, to whom shall we go? You have the words of eternal life.' },
  { reference: 'Proverbs 16:9', text: 'In their hearts humans plan their course, but the Lord establishes their steps.' },
  { reference: 'Romans 12:6', text: 'We have different gifts, according to the grace given to each of us.' },
  { reference: 'Revelation 1:8', text: 'I am the Alpha and the Omega, says the Lord God, who is, and who was, and who is to come, the Almighty.' },
  { reference: 'Psalm 25:14', text: 'The Lord confides in those who fear him; he makes his covenant known to them.' },
  { reference: '2 Corinthians 5:21', text: 'God made him who had no sin to be sin for us, so that in him we might become the righteousness of God.' },
  { reference: 'Matthew 12:36', text: 'But I tell you that everyone will have to give account on the day of judgment for every empty word they have spoken.' },
  { reference: 'John 1:14', text: 'The Word became flesh and made his dwelling among us. We have seen his glory, the glory of the one and only Son, who came from the Father, full of grace and truth.' },
  { reference: 'Psalm 22:24', text: 'For he has not despised or scorned the suffering of the afflicted one; he has not hidden his face from him but has listened to his cry for help.' },
  { reference: 'Galatians 3:28', text: 'There is neither Jew nor Gentile, neither slave nor free, nor is there male and female, for you are all one in Christ Jesus.' },
  { reference: 'Isaiah 9:6', text: 'For to us a child is born, to us a son is given, and the government will be on his shoulders. And he will be called Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace.' },
  { reference: 'Hebrews 7:25', text: 'Therefore he is able to save completely those who come to God through him, because he always lives to intercede for them.' },
  { reference: 'Psalm 118:24', text: 'The Lord has done it this very day; let us rejoice today and be glad.' },
  { reference: 'Romans 15:4', text: 'For everything that was written in the past was written to teach us, so that through the endurance taught in the Scriptures and the encouragement they provide we might have hope.' },
  { reference: 'John 4:23', text: 'Yet a time is coming and has now come when the true worshipers will worship the Father in the Spirit and in truth, for they are the kind of worshipers the Father seeks.' },
  { reference: 'Luke 24:6', text: 'He is not here; he has risen! Remember how he told you, while he was still with you in Galilee.' },
  { reference: 'Matthew 7:24', text: 'Therefore everyone who hears these words of mine and puts them into practice is like a wise man who built his house on the rock.' },
  { reference: 'Psalm 91:2', text: 'I will say of the Lord, He is my refuge and my fortress, my God, in whom I trust.' },
  { reference: 'Ephesians 6:11', text: 'Put on the full armor of God, so that you can take your stand against the devil\'s schemes.' },
  { reference: '1 John 4:8', text: 'Whoever does not love does not know God, because God is love.' },
  { reference: 'Psalm 33:4', text: 'For the word of the Lord is right and true; he is faithful in all he does.' },
  { reference: 'Isaiah 57:15', text: 'For this is what the high and exalted One says—he who lives forever, whose name is holy: I live in a high and holy place, but also with the one who is contrite and lowly in spirit.' },
  { reference: 'Colossians 1:13', text: 'For he has rescued us from the dominion of darkness and brought us into the kingdom of the Son he loves.' },
  { reference: 'Romans 12:13', text: 'Share with the Lord\'s people who are in need. Practice hospitality.' },
  { reference: 'John 17:3', text: 'Now this is eternal life: that they know you, the only true God, and Jesus Christ, whom you have sent.' },
  { reference: 'Psalm 50:15', text: 'Call on me in the day of trouble; I will deliver you, and you will honor me.' },
  { reference: 'Matthew 5:13', text: 'You are the salt of the earth. But if the salt loses its saltiness, how can it be made salty again?' },
  { reference: 'Proverbs 21:21', text: 'Whoever pursues righteousness and love finds life, prosperity and honor.' },
  { reference: 'Acts 10:34', text: 'Then Peter began to speak: I now realize how true it is that God does not show favoritism.' },
  { reference: 'Psalm 65:11', text: 'You crown the year with your bounty, and your carts overflow with abundance.' },
  { reference: '1 Peter 3:15', text: 'But in your hearts revere Christ as Lord. Always be prepared to give an answer to everyone who asks you to give the reason for the hope that you have.' },
  { reference: 'Hebrews 2:18', text: 'Because he himself suffered when he was tempted, he is able to help those who are being tempted.' },
  { reference: 'Matthew 11:25', text: 'At that time Jesus said, I praise you, Father, Lord of heaven and earth, because you have hidden these things from the wise and learned, and revealed them to little children.' },
  { reference: 'Romans 8:14', text: 'For those who are led by the Spirit of God are the children of God.' },
  { reference: 'Psalm 119:50', text: 'My comfort in my suffering is this: Your promise preserves my life.' },
  { reference: 'John 15:9', text: 'As the Father has loved me, so have I loved you. Now remain in my love.' },
  { reference: 'Isaiah 40:3', text: 'A voice of one calling: In the wilderness prepare the way for the Lord; make straight in the desert a highway for our God.' },
  { reference: 'Galatians 5:16', text: 'So I say, walk by the Spirit, and you will not gratify the desires of the flesh.' },
  { reference: 'Psalm 92:5', text: 'How great are your works, Lord, how profound your thoughts!' },
  { reference: 'Ephesians 2:4', text: 'But because of his great love for us, God, who is rich in mercy, made us alive with Christ even when we were dead in transgressions.' },
  { reference: 'Luke 1:45', text: 'Blessed is she who has believed that the Lord would fulfill his promises to her!' },
  { reference: '1 Corinthians 1:18', text: 'For the message of the cross is foolishness to those who are perishing, but to us who are being saved it is the power of God.' },
  { reference: 'Psalm 145:13', text: 'Your kingdom is an everlasting kingdom, and your dominion endures through all generations.' },
  { reference: 'Romans 12:16', text: 'Live in harmony with one another. Do not be proud, but be willing to associate with people of low position.' },
  { reference: 'Matthew 6:26', text: 'Look at the birds of the air; they do not sow or reap or store away in barns, and yet your heavenly Father feeds them.' },
  { reference: 'John 12:32', text: 'And I, when I am lifted up from the earth, will draw all people to myself.' },
  { reference: 'Proverbs 30:5', text: 'Every word of God is flawless; he is a shield to those who take refuge in him.' },
  { reference: 'Psalm 119:103', text: 'How sweet are your words to my taste, sweeter than honey to my mouth!' },
  { reference: 'Isaiah 62:11', text: 'The Lord has made proclamation to the ends of the earth: Say to Daughter Zion, See, your Savior comes!' },
  { reference: 'Revelation 22:17', text: 'The Spirit and the bride say, Come! And let the one who hears say, Come! Let the one who is thirsty come; and let the one who wishes take the free gift of the water of life.' },
  { reference: '2 Corinthians 13:14', text: 'May the grace of the Lord Jesus Christ, and the love of God, and the fellowship of the Holy Spirit be with you all.' },
]
